# Generated by Django 5.1.7 on 2025-04-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.URLField(max_length=500)),
                (
                    "youtube_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("subscriber_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("video_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-subscriber_count"],
                "indexes": [
                    models.Index(fields=["name"], name="youtube_sta_name_6681eb_idx"),
                    models.Index(
                        fields=["youtube_id"], name="youtube_sta_youtube_e97086_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("image", models.URLField(max_length=500)),
                ("youtube_id", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="youtube_statement.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment_text", models.TextField()),
                ("youtube_id", models.CharField(max_length=100, unique=True)),
                ("author_name", models.CharField(max_length=255)),
                (
                    "author_channel_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("like_count", models.IntegerField(default=0)),
                (
                    "sentiment",
                    models.IntegerField(
                        choices=[(1, "Positive"), (2, "Negative"), (3, "Neutral")],
                        default=3,
                    ),
                ),
                ("sentiment_score", models.FloatField(default=0.0)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="youtube_statement.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["youtube_id"], name="youtube_sta_youtube_2e2718_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["name"], name="youtube_sta_name_86116d_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["youtube_id"], name="youtube_sta_youtube_a43b3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["sentiment"], name="youtube_sta_sentime_be11d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="youtube_sta_created_52fdab_idx"
            ),
        ),
    ]
