# Generated by Django 5.1.7 on 2025-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
