# Generated by Django 5.1.7 on 2025-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0002_alter_video_youtube_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_comment_bank",
            field=models.BooleanField(default=False),
        ),
    ]
