# Generated by Django 5.1.7 on 2025-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0003_comment_is_comment_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="type",
            field=models.IntegerField(
                choices=[(1, "يوتيوب"), (2, "تويتر"), (3, "تيك توك")], default=1
            ),
        ),
    ]
