# Generated by Django 5.1.7 on 2025-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0004_channel_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="is_comment_bank",
            new_name="in_bank",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author_channel_id",
            new_name="user_name",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author_name",
        ),
        migrations.AddField(
            model_name="comment",
            name="translated_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="user_image",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
