# Generated by Django 5.1.7 on 2025-05-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0005_rename_is_comment_bank_comment_in_bank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
