# Generated by Django 5.1.7 on 2025-05-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0006_video_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="url",
            field=models.URLField(
                default="https://www.youtube.com/@PBSNewsHour", max_length=500
            ),
            preserve_default=False,
        ),
    ]
