# Generated by Django 5.1.7 on 2025-05-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0007_channel_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="youtube_id",
            field=models.CharField(max_length=100),
        ),
    ]
