# Generated by Django 5.1.7 on 2025-05-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0008_alter_comment_youtube_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(default="212dsdsds", max_length=100),
            preserve_default=False,
        ),
    ]
