# Generated by Django 5.1.7 on 2025-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_statement", "0009_alter_video_youtube_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author_channel_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
